
# ██╗░░░░░███████╗░██████╗██╗███╗░░██╗██████╗░██████╗░░█████╗░██╗░░██╗██╗░░░██╗
# ██║░░░░░██╔════╝██╔════╝██║████╗░██║██╔══██╗██╔══██╗██╔══██╗╚██╗██╔╝╚██╗░██╔╝
# ██║░░░░░█████╗░░╚█████╗░██║██╔██╗██║██████╔╝██████╔╝██║░░██║░╚███╔╝░░╚████╔╝░
# ██║░░░░░██╔══╝░░░╚═══██╗██║██║╚████║██╔═══╝░██╔══██╗██║░░██║░██╔██╗░░░╚██╔╝░░
# ███████╗███████╗██████╔╝██║██║░╚███║██║░░░░░██║░░██║╚█████╔╝██╔╝╚██╗░░░██║░░░
# ╚══════╝╚══════╝╚═════╝░╚═╝╚═╝░░╚══╝╚═╝░░░░░╚═╝░░╚═╝░╚════╝░╚═╝░░╚═╝░░░╚═╝░░░

localServer:
  port: 25578 # порт локального сервера
  motd: '' # MOTD локального сервера
  onlineMode: false # true - лицензионный, false - пиратский
  serverName: '' # название удаленного сервера
  remoteServer: '' # айпи удаленного сервера
  remotePort: 25565 # порт удаленного сервера

vkBot:
  enable: true # отправлять логи в ВК
  token: '' # токен для бота ВК (longpoll v5.130)
  user: '' # ID пользователя ВК
  logLevel: 'full' # уровень логов для ВК (full - полные, messages - сообщения и команды)

modules:
  packetLogger: false # отправлять логи пакетов
  chatLogger: true # отправлять логи чата и команд
